In [1]:
import sys 
sys.path.insert(0,"../../../../utilities/")
import data_utils
sys.path.insert(0,"../../src/")
import util, mrf
import os
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix

In [2]:
resolution = 25000
input_file = "../../data/test_input_chr1.txt"
bin_file = "../../data/test_bin_chr1.bed"
hic_file = "../../data/test_Hi-C_chr1.txt"

In [3]:
input_data = util.readData(input_file)
bin_data = util.readBedGraph(bin_file)
(n, d) = input_data.shape
edges = util.create_hic_matrix(hic_file, n)

In [37]:
boundaries = []
lens = []
for i in range(len(bin_data)-1):    
    boundaries.append(bin_data[i][2] != bin_data[i+1][1])
    lens.append((bin_data[i][2]-bin_data[i][1])!=25000)

In [51]:
edge_data = []
edge_data.append([0,1,1])
for i in range(input_data.shape[0]-2):
    edge_data.append([i+1,i,1])
    edge_data.append([i+1,i+2,1])
edge_data.append([input_data.shape[0]-1,input_data.shape[0]-2,1])
edge_data = np.array(edge_data)

In [15]:
#### GMM ####

from sklearn import mixture
gmm_model = mixture.GaussianMixture(n_components=10, covariance_type='full')
gmm_model.fit(input_data)
gmm_labels = gmm_model.predict(input_data)

In [16]:
#### GMM+HMM ####

from hmmlearn import hmm
gmm_hmm_model = hmm.GaussianHMM(n_components=10, covariance_type='full')
gmm_hmm_model.fit(input_data)
gmm_hmm_labels = gmm_hmm_model.decode(input_data)

In [48]:
np.unique(gmm_labels, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 303, 1023, 1100,  977,  630, 1250,  961, 1842,  158,  994]))

In [50]:
np.unique(gmm_hmm_labels[1], return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([ 941, 1726,  952, 1281,  706,  819,  584,  696,  696,  837]))

In [10]:
labels_df = 
print(len(MAP_estimate[1]), len(label))

9238 9238


In [18]:
labels_df = pd.DataFrame(bin_data)
labels_df['GMM_labels'] = gmm_labels
labels_df['GMM_HMM_labels'] = gmm_hmm_labels[1]

In [20]:
a = labels_df.groupby(['GMM_labels','GMM_HMM_labels']).size()
a_table = a.unstack(level=0)

In [46]:
a_table

GMM_labels          0      1      2      3      4      5      6       7  \
GMM_HMM_labels                                                            
0                 NaN    NaN   79.0   73.0    NaN    3.0  786.0     NaN   
1                 NaN   29.0    NaN    NaN    NaN    NaN    NaN  1697.0   
2                 NaN  596.0    2.0    NaN  340.0    NaN    NaN    14.0   
3               293.0    NaN    NaN  359.0    NaN    8.0    NaN     NaN   
4                 1.0    NaN    8.0    NaN   91.0  599.0    NaN     NaN   
5                 NaN    NaN  631.0    NaN   24.0   24.0  140.0     NaN   
6                 9.0    NaN    1.0    1.0    7.0  337.0    NaN     NaN   
7                 NaN  387.0  174.0    NaN    4.0    NaN    NaN   131.0   
8                 NaN   11.0  204.0    NaN  164.0  166.0    NaN     NaN   
9                 NaN    NaN    1.0  544.0    NaN  113.0   35.0     NaN   

GMM_labels          8      9  
GMM_HMM_labels                
0                 NaN    NaN  
1                 NaN    NaN  
2                 NaN    NaN  
3                 NaN  621.0  
4                 7.0    NaN  
5                 NaN    NaN  
6                 NaN  229.0  
7                 NaN    NaN  
8               151.0    NaN  
9                 NaN  144.0

In [44]:
labels_map = {}
for l in range(len(a_table)):
    labels_map[l] = np.argmax(a_table[l])

In [45]:
labels_map

{0: 3, 1: 2, 2: 5, 3: 9, 4: 2, 5: 4, 6: 0, 7: 1, 8: 8, 9: 3}

In [52]:
#### GMM+chain HMRF ####

class Args:
  i = "../../data/test_input_chr1.txt"
  hic = "../../data/test_Hi-C_chr1.txt"
  w = 25000
  n = 10
  o = "results"
  g = "../../data/test_bin_chr1.bed"
args=Args()
hmrf = mrf.MarkovRandomField(n=n, edges=edge_data, obs=input_data, args=args)
hmrf.init_gmm()
hmrf.init_trans()
hmrf.solve()


label frequencies at iteration 0 is (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 763,  527, 1258,  655, 1018,  985, 1121, 1378,  443, 1090]))
label frequencies at iteration 1 is (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 708,  588,  879,  594,  863, 1345, 1141, 1383,  570, 1167]))
label frequencies at iteration 2 is (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 750,  616,  752,  674,  850, 1525,  991, 1367,  289, 1424]))
label frequencies at iteration 3 is (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 820,  573,  743,  682,  891, 1562,  755, 1382,  240, 1590]))
label frequencies at iteration 4 is (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 850,  444,  769,  699,  881, 1580,  693, 1413,  218, 1691]))
label frequencies at iteration 5 is (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 862,  340,  760,  750,  860, 1611,  687, 1431,  213, 1724]))
label frequencies at iteration 6 is (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 898,  223,  697,  760,  864, 1654,  634, 1451,

In [15]:
np.unique(label, return_counts=True)
print((label[1:]!=label[:-1]).sum())

912


In [17]:
np.unique(MAP_estimate[1], return_counts=True)
print((MAP_estimate[1][1:]!=MAP_estimate[1][:-1]).sum())

563


In [43]:
from scipy.special import logsumexp
logsumexp(hmrf.edge_potential)

-2.220446049250313e-16

In [15]:
fithic_data = pd.read_csv("../../../../data/K562/Hi-C/fithic_25000/chr1_chr1.txt", sep = "\t")

In [16]:
fithic_data.columns

Index(['chr1', 'fragmentMid1', 'chr2', 'fragmentMid2', 'contactCount',
       'p-value', 'q-value', 'bias1', 'bias2', 'ExpCC'],
      dtype='object')

In [19]:
fithic_significants = fithic_data.nsmallest(20000,'q-value')

In [20]:
lamin_tsa = pd.read_csv("../../../../data/K562/genomic-assays/TSA-seq/LaminA_TSA-seq_binned25000.bedgraph", sep = "\t", header = None)

In [22]:
lamin_tsa[lamin_tsa.iloc[:,0]=='chr1']

0     1     2         3
0     chr1     0     1 -0.600856
1     chr1     1     2 -0.897333
2     chr1     2     3 -1.813977
3     chr1     3     4 -1.221924
4     chr1     4     5 -1.475075
5     chr1     5     6 -0.844969
6     chr1     6     7 -1.230400
7     chr1     7     8 -0.477270
8     chr1     8     9 -0.312351
9     chr1     9    10 -1.215879
10    chr1    10    11 -1.350380
11    chr1    11    12 -0.046864
12    chr1    12    13 -0.587135
13    chr1    13    14 -1.455083
14    chr1    14    15 -1.425706
15    chr1    15    16 -1.195983
16    chr1    16    17 -0.767046
17    chr1    17    18 -0.326626
18    chr1    18    19 -0.889380
19    chr1    19    20 -0.363487
20    chr1    20    21 -0.528375
21    chr1    21    22 -0.900393
22    chr1    22    23  0.398464
23    chr1    23    24 -0.824703
24    chr1    24    25 -1.407436
25    chr1    25    26 -1.365466
26    chr1    26    27 -1.148228
27    chr1    27    28 -1.250712
28    chr1    28    29 -1.094454
29    chr1    29    30 -1.431990
...    ...   ...   ...       ...
9940  chr1  9940  9941  0.578350
9941  chr1  9941  9942  0.876943
9942  chr1  9942  9943  0.896196
9943  chr1  9943  9944  0.854533
9944  chr1  9944  9945  0.884170
9945  chr1  9945  9946  0.888927
9946  chr1  9946  9947  0.802003
9947  chr1  9947  9948  0.911931
9948  chr1  9948  9949  0.728450
9949  chr1  9949  9950  0.826569
9950  chr1  9950  9951  0.636742
9951  chr1  9951  9952  0.660284
9952  chr1  9952  9953  0.990547
9953  chr1  9953  9954  0.713061
9954  chr1  9954  9955  0.862429
9955  chr1  9955  9956  0.667090
9956  chr1  9956  9957  0.721174
9957  chr1  9957  9958  0.000000
9958  chr1  9958  9959  0.000000
9959  chr1  9959  9960  0.000000
9960  chr1  9960  9961  0.000000
9961  chr1  9961  9962  0.007954
9962  chr1  9962  9963  1.052094
9963  chr1  9963  9964  1.118528
9964  chr1  9964  9965  1.043739
9965  chr1  9965  9966  0.919998
9966  chr1  9966  9967  0.952318
9967  chr1  9967  9968  0.516811
9968  chr1  9968  9969  0.433904
9969  chr1  9969  9970 -0.097203

[9970 rows x 4 columns]